services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"
